### PR TITLE
New format for GoogleBot Mobile and support for BingBot Mobile

### PR DESCRIPTION
**Pull request by behid**
This PR will adapt the mobile-bot detection of goolebot since they changed their user agent:
http://searchengineland.com/google-change-smartphone-user-agent-googlebot-iphone-android-april-18th-244779

Also I've added support for BingBot Mobile:
https://www.bing.com/webmaster/help/which-crawlers-does-bing-use-8c184ec0?ocid=wmblog

### CODE REVIEW

**Comment by leroy0211** [comment]
Please merge this, since this has broken the google mobile crawler

**Comment by Tehem** [comment]
This will not correctly match Google SmartPhone User-Agent. See official Google doc : https://support.google.com/webmasters/answer/1061943?hl=fr.

The User-Agent has a space character after 'compatible' and 'Googlebot/2.1', which make the match fail. The rule should had a possible white space:

`req.http.User-Agent ~ "\(compatible.?; Googlebot/2.1.?; \+http://www.google.com/bot.html"`


See my closed #34 for example (I created it before discovering yours was the same thing).

**Comment by behid** [comment]
Good catch @Tehem, I think I've updated it to be 100% correct now.

**Comment by KeyserSosa** [comment]
lgtm

**Pull request merged**
